version: '3'
services:
  shell:
    build: .
    image: hotlouddusty_server_shell
    stdin_open: true
    tty: true
    entrypoint: /bin/sh
    volumes:
      - .:/app

  jupyter:
    image: hotlouddusty_server_shell
    ports:
      - "${HOST_PORT_JUPYTER:-8888}:${HOST_PORT_JUPYTER:-8888}"
    entrypoint: |
      jupyter lab scripts/ --ip=0.0.0.0 --port=${HOST_PORT_JUPYTER:-8888} --allow-root --no-browser
    volumes:
      - .:/app
    depends_on:
      - shell

  pipenv:
    image: hotlouddusty_server_shell
    entrypoint: pipenv
    volumes:
      - .:/app
    depends_on:
      - shell

  python:
    image: hotlouddusty_server_shell
    entrypoint: python scripts/
    volumes:
      - .:/app
    depends_on:
      - shell
